Composition {
	CurrentTime = 0,
	RenderRange = { 0, 94 },
	GlobalRange = { 0, 94 },
	CurrentID = 4,
	HiQ = true,
	PlaybackUpdateMode = 0,
	StereoMode = false,
	Version = "DaVinci Resolve Studio 21.0.3.0007",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		MediaIn1 = Loader {
			ExtentSet = true,
			CustomData = {
				MediaProps = {
					MEDIA_AUDIO_TRACKS_DESC = {
						{
							MEDIA_AUDIO_BIT_DEPTH = 32,
							MEDIA_AUDIO_FRAME_RATE = 24,
							MEDIA_AUDIO_NUM_CHANNELS = 2,
							MEDIA_AUDIO_SAMPLE_RATE = 48000,
							MEDIA_AUDIO_START_TIME = 0,
							MEDIA_AUDIO_TRACK_ID = "92ab3316-db9c-4110-b3e3-31efef3fdcb8",
							MEDIA_AUDIO_TRACK_NAME = "Fusion Clip 1"
						},
						{
							MEDIA_AUDIO_BIT_DEPTH = 32,
							MEDIA_AUDIO_FRAME_RATE = 24,
							MEDIA_AUDIO_NUM_CHANNELS = 2,
							MEDIA_AUDIO_SAMPLE_RATE = 48000,
							MEDIA_AUDIO_START_TIME = 0,
							MEDIA_AUDIO_TRACK_ID = "Timeline Audio",
							MEDIA_AUDIO_TRACK_NAME = "Timeline Audio [phase2-risk]"
						}
					},
					MEDIA_AUDIO_TRACKS_NUM = 2,
					MEDIA_HAS_AUDIO = true,
					MEDIA_HEIGHT = 1350,
					MEDIA_ID = "92ab3316-db9c-4110-b3e3-31efef3fdcb8",
					MEDIA_IS_SOURCE_RES = false,
					MEDIA_LAYERS_IN_OUT_LIST = {
						{
							0,
							95
						}
					},
					MEDIA_MARK_IN = 0,
					MEDIA_MARK_OUT = 94,
					MEDIA_NAME = "Fusion Clip 1",
					MEDIA_NUM_FRAMES = 95,
					MEDIA_NUM_LAYERS = 1,
					MEDIA_PAR = 1,
					MEDIA_SRC_FRAME_RATE = 24,
					MEDIA_START_FRAME = 0,
					MEDIA_WIDTH = 1080,
				},
			},
			Inputs = {
				GlobalOut = Input { Value = 94, },
				AudioTrack = Input { Value = FuID { "Timeline Audio" }, },
				Layer = Input { Value = "0", },
				ClipTimeEnd = Input { Value = 94, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				DeepOutputMode = Input {
					Value = 0,
					Disabled = true,
				},
			},
			Version = 1,
			Clips = {
				Clip {
					ID = "Clip1",
					Length = 95,
					LengthSetManually = true,
					GlobalEnd = 94,
					TrimOut = 94,
				}
			}
		},
		BrightnessContrast1 = BrightnessContrast {
			Inputs = {
				Gain = Input { Value = 0.25, },
				Input = Input {
					SourceOp = "MediaIn1",
					Source = "Output",
				}
			},
		},
		MediaOut1 = Saver {
			Inputs = {
				Index = Input { Value = "0", },
				Input = Input {
					SourceOp = "BrightnessContrast1",
					Source = "Output",
				}
			},
		}
	},
	Frames = {
	},
	Prefs = {
		Comp = {
			Paths = {
				Map = {
					["ResolveCaches:"] = "/Users/zhangxiaolong/Movies/CacheClip/11f51ae0-a97b-4b66-af9b-ebd61b15b92a/891cffff-e9cf-4b9f-8d12-41d7375edcb3/a64f8abb-f258-48c1-b01e-ba0b41a31eb5/Fusion",
				},
			},
			Interactive = {
				Proxy = {
					Scale = 1,
				},
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
				DepthPreview = 3,
				Rate = 24,
				Width = 1080,
				DepthFull = 3,
				Height = 1350,
				DepthInteractive = 3,
			},
			Unsorted = {
				GlobalEnd = 94
			},
			Views = {
				View1 = {
				},
			},
			SpellCheck = {
			}
		}
	},
}