Composition {
	CurrentTime = 0,
	RenderRange = { 0, 46 },
	GlobalRange = { -10479, 25537 },
	CurrentID = 4,
	HiQ = true,
	PlaybackUpdateMode = 0,
	StereoMode = false,
	Version = "DaVinci Resolve Studio 21.0.3.0007",
	SavedOutputs = 0,
	HeldTools = 0,
	DisabledTools = 0,
	LockedTools = 0,
	AudioOffset = 0,
	Resumable = true,
	OutputClips = {
	},
	Tools = {
		MediaIn1 = Loader {
			ExtentSet = true,
			CustomData = {
				MediaProps = {
					FUSION_MARKERS_INFO_LIST = {
						{
							FUSION_MARKER_COLOR = "ResolveColorBlue",
							FUSION_MARKER_COLOR_VALUE = 671121379,
							FUSION_MARKER_DURATION = 0,
							FUSION_MARKER_ID = 0,
							FUSION_MARKER_NAME = "Chapter 21",
							FUSION_MARKER_NOTE = "",
							FUSION_MARKER_PIXMAP_NAME = ":/Common/FlagsAndMarkers/MarkerBlue",
							FUSION_MARKER_POSITION = -10479,
							FUSION_MARKER_TYPE = "FUSION_MARKER_TYPE_CLIP"
						},
						{
							FUSION_MARKER_COLOR = "ResolveColorBlue",
							FUSION_MARKER_COLOR_VALUE = 671121379,
							FUSION_MARKER_DURATION = 0,
							FUSION_MARKER_ID = 2767,
							FUSION_MARKER_NAME = "Chapter 22",
							FUSION_MARKER_NOTE = "",
							FUSION_MARKER_PIXMAP_NAME = ":/Common/FlagsAndMarkers/MarkerBlue",
							FUSION_MARKER_POSITION = -7714,
							FUSION_MARKER_TYPE = "FUSION_MARKER_TYPE_CLIP"
						},
						{
							FUSION_MARKER_COLOR = "ResolveColorBlue",
							FUSION_MARKER_COLOR_VALUE = 671121379,
							FUSION_MARKER_DURATION = 0,
							FUSION_MARKER_ID = 19331,
							FUSION_MARKER_NAME = "Chapter 23",
							FUSION_MARKER_NOTE = "",
							FUSION_MARKER_PIXMAP_NAME = ":/Common/FlagsAndMarkers/MarkerBlue",
							FUSION_MARKER_POSITION = 8833,
							FUSION_MARKER_TYPE = "FUSION_MARKER_TYPE_CLIP"
						},
						{
							FUSION_MARKER_COLOR = "ResolveColorBlue",
							FUSION_MARKER_COLOR_VALUE = 671121379,
							FUSION_MARKER_DURATION = 0,
							FUSION_MARKER_ID = 32420,
							FUSION_MARKER_NAME = "Chapter 24",
							FUSION_MARKER_NOTE = "",
							FUSION_MARKER_PIXMAP_NAME = ":/Common/FlagsAndMarkers/MarkerBlue",
							FUSION_MARKER_POSITION = 21909,
							FUSION_MARKER_TYPE = "FUSION_MARKER_TYPE_CLIP"
						},
						{
							FUSION_MARKER_COLOR = "ResolveColorBlue",
							FUSION_MARKER_COLOR_VALUE = 671121379,
							FUSION_MARKER_DURATION = 0,
							FUSION_MARKER_ID = 34567,
							FUSION_MARKER_NAME = "Chapter 25",
							FUSION_MARKER_NOTE = "",
							FUSION_MARKER_PIXMAP_NAME = ":/Common/FlagsAndMarkers/MarkerBlue",
							FUSION_MARKER_POSITION = 24054,
							FUSION_MARKER_TYPE = "FUSION_MARKER_TYPE_CLIP"
						}
					},
					MEDIA_AUDIO_TRACKS_DESC = {
						{
							MEDIA_AUDIO_BIT_DEPTH = 32,
							MEDIA_AUDIO_FRAME_RATE = 23.976023976024,
							MEDIA_AUDIO_NUM_CHANNELS = 2,
							MEDIA_AUDIO_SAMPLE_RATE = 48000,
							MEDIA_AUDIO_START_TIME = 0,
							MEDIA_AUDIO_TRACK_ID = "285d411b-ec61-480b-b866-bb70839104d6",
							MEDIA_AUDIO_TRACK_NAME = "bleach_original_ep060_bd_1080p_24fps_hevc.mkv"
						},
						{
							MEDIA_AUDIO_BIT_DEPTH = 32,
							MEDIA_AUDIO_FRAME_RATE = 23.976023976024,
							MEDIA_AUDIO_NUM_CHANNELS = 2,
							MEDIA_AUDIO_SAMPLE_RATE = 48000,
							MEDIA_AUDIO_START_TIME = 0,
							MEDIA_AUDIO_TRACK_ID = "Timeline Audio",
							MEDIA_AUDIO_TRACK_NAME = "Timeline Audio [recipe-authoring]"
						}
					},
					MEDIA_AUDIO_TRACKS_NUM = 2,
					MEDIA_FORMAT_TYPE = "MKV",
					MEDIA_HAS_AUDIO = true,
					MEDIA_HEIGHT = 1080,
					MEDIA_ID = "285d411b-ec61-480b-b866-bb70839104d6",
					MEDIA_IS_SOURCE_RES = true,
					MEDIA_MARK_IN = 0,
					MEDIA_MARK_OUT = 46,
					MEDIA_NAME = "bleach_original_ep060_bd_1080p_24fps_hevc.mkv",
					MEDIA_NUM_FRAMES = 36017,
					MEDIA_NUM_LAYERS = 1,
					MEDIA_PAR = 1,
					MEDIA_PATH = "/Users/zhangxiaolong/Desktop/anime-material-library/sources/bleach/original/bleach_original_ep060_bd_1080p_24fps_hevc.mkv",
					MEDIA_SRC_FRAME_RATE = 23.976023976024,
					MEDIA_START_FRAME = -10479,
					MEDIA_WIDTH = 1440
				},
			},
			Inputs = {
				GlobalIn = Input { Value = -10479, },
				GlobalOut = Input { Value = 25537, },
				AudioTrack = Input { Value = FuID { "Timeline Audio" }, },
				Layer = Input { Value = "0", },
				ClipTimeStart = Input { Value = -10479, },
				ClipTimeEnd = Input { Value = 25537, },
				["Gamut.SLogVersion"] = Input { Value = FuID { "SLog2" }, },
				DeepOutputMode = Input {
					Value = 0,
					Disabled = true,
				},
			},
			Version = 1,
			Clips = {
				Clip {
					ID = "Clip1",
					Multiframe = true,
					Filename = "/Users/zhangxiaolong/Desktop/anime-material-library/sources/bleach/original/bleach_original_ep060_bd_1080p_24fps_hevc.mkv",
					Length = 36017,
					LengthSetManually = true,
					GlobalStart = -10479,
					GlobalEnd = 25537,
					TrimIn = -10479,
					TrimOut = 25537,
				}
			}
		},
		MotionBlurTransition = DirectionalBlur {
			Inputs = {
				Length = Input { Expression = "0.24 * max(0, 1 - abs(time - 23) / 15)", },
				Input = Input {
					SourceOp = "MediaIn1",
					Source = "Output",
				}
			},
		},
		MediaOut1 = Saver {
			Inputs = {
				Index = Input { Value = "0", },
				Input = Input {
					SourceOp = "MotionBlurTransition",
					Source = "Output",
				}
			},
		}
	},
	Frames = {
	},
	Prefs = {
		Comp = {
			Paths = {
				Map = {
					["ResolveCaches:"] = "/Users/zhangxiaolong/Movies/CacheClip/c6979268-84f9-4a9e-94da-4369d5f7f5db/0fa620c1-69af-4808-9eab-c940882fca7a/686b68f2-63a3-45f4-af75-b77fd965c22e/Fusion",
				},
			},
			Interactive = {
				Proxy = {
					Scale = 1,
				},
			},
			FrameFormat = {
				GuideRatio = 1.77777777777778,
				DepthPreview = 3,
				Rate = 24,
				Width = 1440,
				DepthFull = 3,
				DepthInteractive = 3,
			},
			Unsorted = {
				GlobalStart = 4294956817,
				GlobalEnd = 25537
			},
			Views = {
				View1 = {
				},
			},
			SpellCheck = {
			}
		}
	},
}